Feature uarm gcode
R2D2-2019/robot_arm pull request #12
Opened 2019-04-16 18:48 UTC by renskekuip1

2019-04-16 19:08 UTC, Kaaserne requested changes
I think the virtual methods can be pure virtual methods. For e.g. `virtual void init() = 0;`. If this is the case ,please add a virtual destructor, if not, then you can leave it as is.

2019-04-16 19:08 UTC, MarcDirven commented on code/headers/robot_arm.hpp
> +        robot_arm_c(r2d2::hardware_usart_c usart_bus);
Most of the functions can take the parameters by `const&`

2019-04-16 19:58 UTC, itzandroidtab commented on code/headers/uarm_gcode_generator_c.hpp
>           * @return char* to buffer
Why is this file called uarm_gcode_generator```_c```.hpp why not just uarm_gcode_generator

2019-04-16 19:59 UTC, itzandroidtab commented on code/main.cpp
> +#include "dof4_diy_c.hpp"
this is a library so it should be with ```<>```

2019-04-16 20:00 UTC, itzandroidtab commented on code/main.cpp
> +#include "dof4_diy_c.hpp"
and the same with the file name why the _c?

2019-04-17 15:18 UTC, MarcDirven commented on code/headers/robot_arm_interface.hpp
> +#include "vector3.hpp"
All .hpp's have to be included with `<>`

2019-04-18 11:15 UTC, itzandroidtab commented
Why would you add a delete? There is probably something differently going wrong

2019-04-18 20:07 UTC, Kaaserne approved these changes

2019-04-18 20:16 UTC, merged